%This script takes the HISTDATA array generated by combineFiles.m when
%run on echo data. It produces histograms for the power and arrival time of
%the echoes for each comb tooth spacing.

%in the past, we haven't seen much variation in the input pulse power
%across traces, so HISTDATA (saved in TRACEHISTOGRAMS.MAT) is not
%normalized.

load('traceHistograms.mat')

%the transmission peak is omitted from HISTDATA by a hard-coded cutoff in
%DOAVG_ECHO.m (1.4us for the data set from 2020-02-27).

%I'm hard-coding the sequence of tooth spacings used, but if necessary
%in future this can instead be pulled from the freqs.txt file
freqs= linspace(0.1,20,200)*1e6;
echoSpacing= 1./freqs;

% make mxn subplot array
m= 10;
n= 2;

for k=1:length(histData)
    echoPower= histData{k}(:,1);
    echoPower= echoPower/max(echoPower);
    echoTime= histData{k}(:,2);
%     
%     echoPower= echoPower(echoTime>0);
%     echoTime= echoTime(echoTime>0);
%     check(k,:)= [length(echoPower),length(echoTime)];
            
    figure(floor((k-1)/m)+1)
    
    % histogram of max echo magnitude in traces of given tooth spacing
    subplot(m,n,1+mod(2*k-2,m*n))
    histogram(echoPower,linspace(0,1,11),...
        'FaceColor',[0.8500, 0.3250, 0.0980]);
    xlim([0,1]);
    title(strcat(num2str(k/10),' MHz spacing'));
    
%     %histogram of arrival times of largest echo in traces of given spacing
%     subplot(m,n,1+mod(3*k-2,m*n))
%     h= histogram(echoTime);
%     title(strcat(num2str(k/10),...
%         ' MHz spacing: ', num2str(10/k),...
%         ' \mus between echoes'))
%     if diff(xlim)>50e-9
%         set(h,'FaceColor',[0.85,0.325,0.098]);
%     end
%     xt= xticks;
%     xticklabels(xt-xt(1));
    
    %plot of echo magnitude and arrival time vs. trace number
    subplot(m,n,1+mod(2*k-1,m*n))
    %
    yyaxis right
    plot(echoPower,'o','LineWidth',2);
    ylim([0,1])
    %
    yyaxis left
    plot(echoTime,'o','LineWidth',2);
    ticks= fliplr(max(echoTime):-echoSpacing(k):0);
    yticks(ticks);
    yticklabels([]);
    
    ax= gca;
    ax.YGrid= 'on';  
    ax.GridAlpha= 0.4;
    title(strcat(num2str(k/10),' MHz spacing'))
end
