%Calculates RF comb produced by FM;
%then calculates optical comb generated by double pass through this RF,
%first for zero delay, then for specified delay.

%Takes center freq (F_C), fm deviation (F_D), modulation freq (F_M) (MHz),
%modulation function (FUNC: choices are sine and triangle wave), time delay
%between passes (DELAY, ns), and a boolean that decides whether or not to apply
%the AOM gain function.

%Returns spectrum as well as time series data of modulated signal and
%modulating signal

function [t,f,rfc,ofc] = doublePassAOM(f_c,f_d,f_m,func)

% beta = w_d/f; %modulation depth

f_s= 4096*2; %sampling rate
dt= 1/f_s; %time step

% T=1/f_c; %carrier period
Tmax= 5000/f_c; %length of signal
t= 0:dt:Tmax-dt; %time range
f= -4096.03+1/Tmax:1/Tmax:4096.03-1/Tmax; %frequency range
size(f)
m= sin(2*pi*f_m*t); %modulating signal (defaults to sine modulation)

if(strcmp(func,'tri')) %note: 'triangle' is a reserved keyword so tri has to be used instead
    disp('triangle time!');
    m= sawtooth(2*pi*f_m*t,1/2);
end

signal= 0.29*fmmod(m,f_c,f_s,f_d);
N= length(signal);
spec= fft(signal); %normalized spectrum

% lspec= spec(1:N/2+1);
rfc= [spec(end-N/2:end),spec(1:N/2+1)];

% lspec= (dt/N)*abs(lspec).^2; %power spectrum
rfc= (dt/N)*abs(rfc).^2;

% lspec(2:end-1)= 2*(lspec(2:end-1)); %negative and positive frequencies are indistinguishable 
% rfc= lspec(1:length(f)); %returns truncated power spectrum (don't need negative frequencies and high frequencies)

signal= signal.^2;           % apply signal twice in double pass.
signal= signal-mean(signal); % result is >0; subtract mean to remove DC.
spec= fft(signal);

ofc= [spec(end-N/2:end),spec(1:N/2+1)];

% lspec= (dt/N)*abs(spec(1:N/2+1)).^2; %power spectrum
ofc= (dt/N)*abs(ofc).^2;


% lspec(2:end-1)= 2*(lspec(2:end-1)); %negative and positive frequencies are indistinguishable 
% ofc= lspec(1:length(f)); %returns truncated power spectrum (don't need negative frequencies and high frequencies)

% f= f-100;

% if applyWA==1
%     f=abs(f);
% end

if(strcmp(useAOM,1))
    bw=25; %aom bandwidth
    f0=100;
    aom=0.8*exp(-((freq-f0)./(2*bw)).^2); %gaussian bw, max diffraction efficiency 110 MHz, 90%
    spectrunc=spectrunc.*aom; %convolve AOM bw with spectrum
end